python video.py --image img20.png --lighting lighting20
python video.py --image img23.png --lighting lighting23
python video.py --image img27.png --lighting lighting27
python video.py --image img28.png --lighting lighting28
python video.py --image img33.png --lighting lighting33
python video.py --image img35.png --lighting lighting35
python video.py --image img59.png --lighting lighting59
python video.py --image img64.png --lighting lighting64
python video.py --image img73.png --lighting lighting73
python video.py --image img76.png --lighting lighting76
python video.py --image img79.png --lighting lighting79
python video.py --image img93.png --lighting lighting93
python video.py --image img96.png --lighting lighting96
python video.py --image img109.png --lighting lighting109
python video.py --image img112.png --lighting lighting112
python video.py --image img113.png --lighting lighting113
python video.py --image img162.png --lighting lighting162
python video.py --image img163.png --lighting lighting163
python video.py --image img211.png --lighting lighting211
python video.py --image img212.png --lighting lighting212
python video.py --image img267.png --lighting lighting267
python video.py --image img268.png --lighting lighting268
python video.py --image img269.png --lighting lighting269
