python video.py --video_name IMG_0058.MOV --gt_lighting
python video.py --video_name IMG_0059.MOV --gt_lighting
python video.py --video_name IMG_0060.MOV --gt_lighting
python video.py --video_name IMG_0061.MOV --gt_lighting
python video.py --video_name IMG_0062.MOV --gt_lighting
python video.py --video_name IMG_0063.MOV --gt_lighting
python video.py --video_name IMG_0064.MOV --gt_lighting
python video.py --video_name IMG_0065.MOV --gt_lighting
python video.py --video_name IMG_0066.MOV --gt_lighting
python video.py --video_name IMG_0067.MOV --gt_lighting
python video.py --video_name IMG_0068.MOV --gt_lighting
python video.py --video_name IMG_0069.MOV --gt_lighting
python video.py --video_name IMG_0070.MOV --gt_lighting
python video.py --video_name IMG_0071.MOV --gt_lighting
